name: ESLint Check

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Installing Node packages
      run: npm install

    - name: Lint with ESLint
      run: npx eslint .